### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by jessesquires** [neonichu/trolldrop#2]
![](http://www.reactionface.info/sites/default/files/images/1287666826226.png)

**Comment by neonichu** [comment]
:joy:

**Comment by neonichu** [comment]
PRs welcome!

**Comment by edwardvalentini** [comment]
how about this?

![687474703a2f2f7777772e7265616374696f6e666163652e696e666f2f73697465732f64656661756c742f66696c65732f696d616765732f313238373636363832363232362e706e67](https://cloud.githubusercontent.com/assets/1571326/14991878/5e0b4d92-1118-11e6-8f74-0f23c3e2e91a.png)
